version: '3'

services:
  node_server:
    build: ./
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network
    command: 'npm run start'

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    volumes:
      - ./user_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
