version: '3'

services:
 mongo:
    image: mongo
    hostname: "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    volumes:
      - ./user_data:/data/db

 node_server:
    build: ./
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    command: 'npm run start'
